### ISSUE TITLE
India Bentity Issues

### ISSUE THREAD

**Issue by nitishnarula** [nitishnarula/antmaps-app#13]
Benoit just discovered that for species Trichomyrmex wroughtoni, India bentity is displayed instead of the smaller bentities inside it for which we have more records. Basically out of 44 records for this species that fall within India, only 2 are marked under India bentity, and the rest are smaller (state-based) bentities.

If I remember correctly, we were told that this situation will not happen for India and Columbia - that records for a species will either be in the larger bentity or one of the bentities inside it (not both). Looks like this is not true.

Matt, I am not sure what the code is and how not to break it. When you get a chance can you look into it?  I understand this was a gross hack because you had hard code the bentitity ids into the frontend. How can we fix this issue? Is it going be another gross hack on top of the already gross hack?

Thanks.

**Comment by mziegler** [comment]
Here's the code that toggles India and Colombia.  It iterates over the list of "overlapping bentities" (India and Columbia,) and shows the India or Colombia bentities if they have a record in the species data we're mapping.

https://github.com/nitishnarula/antmaps-app/blob/master/js/speciesMode.js#L468-L477 

So it sounds we want to do this : show India/Colombia if the species-data has a record for India/Colombia, unless it has a record for one of the bentities inside of India/Colombia, respectively.

My code for this isn't very well documented, so I'll clean it up a bit and fix this bug.  I've been unable to run AntMaps on my machine for some reason, (but I haven't spent that much time trying to figure it out,) so right now I don't have a way to test it, but I'll figure something out.

**Comment by nitishnarula** [comment]
Matt, 

From Benoit's last email it seems that such cases need to be fixed on the data-side of things. In this situation, the two "India" records were to be marked as 'Redundant' which actually excludes them from being displayed on antmaps. So this wasn't supposed to be resolved in the front-end after all. However, I suspect that this may not be the last word on this issue. I will close this issue for now.
